### PR TITLE
Skeleton game controller

### PR DESCRIPTION
**Pull request by hayli**

### CODE REVIEW

**Comment by hayli** [comment]
testing comments

**Comment by allencoin** [comment]
Looks like we can't automatically merge this. I'll look into it to see if I can figure out why.

**Comment by hayli** [comment]
Hi all,

I have actually resolved all the conflicts in my branch with the the skeleton game controller and model with just a name field. I am not sure how the db migrations would work in merges so I have left this till we ask Ken tomorrow.

Otherwise all the other branches merged without a problem and builds are successful.

We can create the development branch tomorrow and setup gitflow after discussion with Ken about db migrations.

Cheers!
Hayli

**Comment by hayli** [comment]
Have updated game controller and unit tests directly on current develop branch.

**Pull request closed without merging**
